LineLength:
  Max: 80
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"  # Arrays use brackets
    "%W": "[]"  # Arrays use brackets

SingleSpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting

StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

inherit_from: test/rubocop/enabled.yml
inherit_from: test/rubocop/disabled.yml
